image: alpine:latest
stages:
  - test
  - build
  - deploy

b1:
  stage: test
  script:
   - echo "Good Morning"
   
b2:
  stage: build
  when: manual
  script:
    - echo "Hello World"
    
b3:
  stage: build
  when: manual
  script:
    - echo "Hello World"

b4:
  stage: deploy
  when: manual
  script:
    - echo "Hello World"