image: starefossen/ruby-node:latest

services:
   - mongo:latest

variables:
  MONGO_URI: 'mongodb://mongo/myapp_test'
  NODE_ENV: 'test'

before_script:
  - apt-get update && apt-get -y install dnsutils

test:
  script:
   - service mongod status