.template1:
  tags:
    - gitlab-org

.template2:
  artifacts:
    expire_in: 1d
    paths:
    - out.txt

release:
  extends: .template1
  extends: .template2
  stage: build
  script:
    - echo 'Hello World" > out.txt