release-chart:
  image: "registry.gitlab.com/gitlab-org/gitlab-omnibus-builder/ruby_docker:0.0.19"
  script:
    - gem install gitlab-qa
    - gitlab-qa Test::Instance::Image registry.gitlab.com/gitlab-org/omnibus-gitlab/gitlab-ee-qa:omnibus-318fea97009ce70a2bfb169042122ee7090a78f4