image: "debian:stretch"

stages:
  - package

build1:
 stage: package
 script:
   - apt-get update
   - apt-get -y install curl
   - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.com/api/v4/projects/3124666/trigger/pipeline
