release-chart:
  image: "alpine:latest"
  script:
    - apk --no-cache add curl
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.com/api/v4/projects/5269015/trigger/pipeline
  only:
    - master