stages:
  - package
  - images
  - qa
  - notification_fail

build1:
 stage: package
 script:
   - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.com/api/v4/projects/3124666/trigger/pipeline

build2:
 stage: images
 script:
   - exit 0
   
build3:
 stage: qa
 script:
   - exit 1
   
slack-notification:
  stage: notification_fail
  script:
    - echo "Failed"
  when: on_failure