.dedicated-runner:
  tags:
    - gitlab-org

.knapsack-state:
  services: []
  cache:
    key: "knapsack"
    paths:
    - knapsack/
  artifacts:
    expire_in: 31d
    paths:
    - knapsack/

knapsack:
  extends: .knapsack-state
  extends: .dedicated-runner
  stage: prepare
  before_script: []
  script:
    - echo 'Hello World"