.template1:
  tags:
    - gitlab-org

.template2:
  artifacts:
    expire_in: 1d
    paths:
    - out.txt

release:
  extends: .knapsack-state
  extends: .dedicated-runner
  stage: build
  script:
    - echo 'Hello World" > out.txt