stages:
  - package
  - images
  - qa
  - notification_fail

build1:
 stage: package
 script:
   - exit 0

build2:
 stage: images
 script:
   - exit 1
   
build3:
 stage: qa
 script:
   - exit 1
   
slack-notification:
  stage: notification_fail
  script:
    - echo "Failed"
  when: on_failure