release-chart:
  script:
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.com/api/v4/projects/balasankarc%2Fcharts.gitlab.io/trigger/pipeline
  only:
    - master