image: "alpine:latest"

.branch_build: &branch_build
  script:
    - echo "${CI_JOB_NAME}"
    - echo "${CI_JOB_NAME[0]}"
    - echo "${CI_JOB_NAME[1]}"
    
.tag_build: &tag_build
  script:
    - echo "${CI_JOB_NAME}"

ubuntu_16.04 branch: *branch_build
ubuntu_16.04: *tag_build