image: "debian:stretch"

stages:
  - package

build1:
 stage: package
 script:
   - apt-get update
   - apt-get -y install git ssh openssh-client
   - echo "$CI_KEY" > ~/.ssh/id_rsa
   - ssh-keyscan -H gitlab.com > ~/.ssh/known_hosts
   - chmod -R 0600 ~/.ssh/
   - git clone git@gitlab.com:balasankarc/samplerepo2.git
   - cd samplerepo2
   - git config user.email "email@example.com"
   - git config user.name "John Doe"
   - touch $$
   - git add .
   - git commit -m "Test"
   - git push origin master
