stages:
  - package
  - package_notification_fail
  - images
  - image_notification_fail
  - qa
  - qa_notification_fail

build1:
 stage: package
 script:
   - exit 0

build2:
 stage: images
 script:
   - exit 1
   
build3:
 stage: qa
 script:
   - exit 0
   
.slack_fail_template: &slack_fail
  script:
    - echo "Failed"
  when: on_failure
  
package-fail:
  stage: package_notification_fail
  <<: *slack_fail
  
image-fail:
  stage: image_notification_fail
  <<: *slack_fail
  
qa-fail:
  stage: qa_notification_fail
  <<: *slack_fail