release-chart:
  image: "alpine:latest"
  script:
    - exit 1
  after_script:
    - echo "I am here"

release-chart2:
  image: "alpine:latest"
  script:
    - exit 0
  after_script:
    - echo "I am here"