image: "alpine:latest"

only-branch:
  script:
    - echo "Hello World"
  only:
    - branches@balasankarc/samplerepo
    
only-tag:
  script:
    - echo "Hello World"
  only:
    - tags@balasankarc/samplerepo