stages:
  - stage_1
  - stage_2
  - stage_3
  - stage_4

job1:
  stage: stage_1
  when: manual
  script: "echo yes"

job2:
  stage: stage_2
  script: "echo yes"

job3:
  stage: stage_3
  script: "echo yes"
  dependencies:
    - job1
